<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-ios18.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>true</ImplicitUsings>
    <IsBindingProject>true</IsBindingProject>
    <RootNamespace>SaturdayMP.XPlugins.iOS</RootNamespace>
    <Title>SaturdayMP.XPlugins.iOS.BEMCheckBox</Title>
    <Authors>Saturday Morning Productions Inc.</Authors>
    <Description>Use the excellent BEMCheckBox in Xamarin iOS applications.  BEMCheckBox allows you to create beautiful, highly customizable, animated checkboxs for iOS.</Description>
    <Copyright>Copyright (c) 2023 Saturday Morning Productions Inc.</Copyright>
    <PackageProjectUrl>https://github.com/saturdaymp/XPlugins.iOS.BEMCheckBox</PackageProjectUrl>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/saturdaymp/XPlugins.iOS.BEMCheckBox</RepositoryUrl>
    <PackageTags>net8.0 net8.0-ios ios ios-binding bemcheckbox checkbox saturdaymp</PackageTags>
    <Company>Saturday Morning Productions Inc.</Company>
    <Product>XPlugins.iOS.BEMCheckBox</Product>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <ObjcBindingCoreSource Include="StructsAndEnums.cs" />
    <ObjcBindingApiDefinition Include="ApiDefinitions.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\LICENSE.txt" Pack="true" PackagePath="" />
    <None Include="..\..\README.md" Pack="true" PackagePath="" />
  </ItemGroup>
  <ItemGroup>
    <NativeReference Include="NativeReferences\BEMCheckBox.xcframework">
      <Kind>Framework</Kind>
      <Frameworks>UIKit</Frameworks>
    </NativeReference>
  </ItemGroup>
</Project>
